import { CookiesProvider } from 'next-client-cookies/server';
import '@/app/globals.css';
import Header from '@/components/Header';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <CookiesProvider>
                    <Header/>
                    {children}
                </CookiesProvider>
            </body>
        </html>
    )
}
